# dlpy 
# Miniconda3 virtual environment on Ubuntu $WSL, 8 core CPU laptop. 
# Environment export date May 22, 2020.  
# Use for my deep learning practice. 
# Github url: git@github.com:JennEYoon/deep-learning.git  
# Main pkgs: Python v 3.8.2, Tensorflow v 2.2.0, Tensorflow-datasets v 3.1.0, 
# keras v 2.3.1, tensorboard v 2.2.1, 
# numpy, pandas, matplotlib, scipy, scikit-learn, jupyter notebook, doctest.    
# ---------------------------  
name: dlpy
channels:
  - sarcasm
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=pyh9f0ad1d_0
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.4.5.1=py38_0
  - cycler=0.10.0=py38_0
  - dbus=1.13.14=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - doctest=2.2.3=h0600cc0_1
  - entrypoints=0.3=py38h32f6830_1001
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - glib=2.63.1=h5a9c865_0
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - importlib-metadata=1.6.0=py38h32f6830_0
  - importlib_metadata=1.6.0=0
  - intel-openmp=2020.1=217
  - ipykernel=5.2.1=py38h23f93f0_0
  - ipython=7.14.0=py38h32f6830_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.17.0=py38h32f6830_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py38h32f6830_1
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py38h32f6830_1
  - kiwisolver=1.2.0=py38hfd86e86_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markupsafe=1.1.1=py38h1e0a361_1
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38hef1b27d_0
  - mistune=0.8.4=py38h1e0a361_1001
  - mkl=2020.1=217
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.0.15=py38ha843d7b_0
  - mkl_random=1.1.0=py38h962f231_0
  - nbconvert=5.6.1=py38h32f6830_1
  - nbformat=5.0.6=py_0
  - ncurses=6.2=he6710b0_1
  - notebook=6.0.3=py38h32f6830_0
  - numpy=1.18.1=py38h4f9e942_0
  - numpy-base=1.18.1=py38hde5b4d6_1
  - openssl=1.1.1g=h7b6447c_0
  - packaging=20.1=py_0
  - pandas=1.0.3=py38h0573a6f_0
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=h049681c_0
  - parso=0.7.0=pyh9f0ad1d_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py38h32f6830_1
  - pickleshare=0.7.5=py38h32f6830_1001
  - pixman=0.38.0=h7b6447c_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - ptyprocess=0.6.0=py_1001
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.16.0=py38h1e0a361_0
  - python=3.8.2=hcf32534_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=py_0
  - pyzmq=19.0.1=py38ha71036d_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - scikit-learn=0.22.1=py38hd81dba3_0
  - scipy=1.4.1=py38h0b6359f_0
  - send2trash=1.5.0=py_0
  - setuptools=46.2.0=py38_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=h62c20be_1
  - terminado=0.8.3=py38h32f6830_1
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py38h7b6447c_1
  - traitlets=4.3.3=py38h32f6830_1
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py38_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - astunparse==1.6.3
    - cachetools==4.1.0
    - chardet==3.0.4
    - dill==0.3.1.1
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.14.3
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - googleapis-common-protos==1.51.0
    - grpcio==1.28.1
    - h5py==2.10.0
    - idna==2.9
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.1
    - markdown==3.2.2
    - oauthlib==3.1.0
    - opt-einsum==3.2.1
    - pip==20.1.1
    - promise==2.3
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyyaml==5.3.1
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow==2.2.0
    - tensorflow-datasets==3.1.0
    - tensorflow-estimator==2.2.0
    - tensorflow-metadata==0.22.0
    - termcolor==1.1.0
    - tqdm==4.46.0
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - wrapt==1.12.1
prefix: /home/jyoon/conda3/envs/dlpy

